# Generated by Django 3.2.4 on 2021-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
