# Generated by Django 3.2.4 on 2021-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=25)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.PositiveBigIntegerField()),
                ('tables_count', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
