# Generated by Django 3.2.4 on 2021-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_reserve_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='amount',
            field=models.IntegerField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='selected',
            field=models.CharField(max_length=500),
        ),
    ]
